import { pdf, markdown, measureText } from '../src/index'

// ── Page 1: Low-level API showcase ──────────────────────────────────────

const doc = pdf()
const W = 612, H = 792

// Read a JPEG for the image test
const catJpeg = await Bun.file(new URL('../cat.jpg', import.meta.url).pathname).bytes()

doc.page(W, H, ctx => {
  // Background header bar
  ctx.rect(0, H - 80, W, 80, '#1a1a2e')

  // Title
  ctx.text('tinypdf Feature Showcase', 40, H - 52, 24, { color: '#e0e0e0' })

  let y = H - 120

  // ── Text rendering ──
  ctx.text('Text Rendering', 40, y, 18, { color: '#16213e' })
  y -= 30
  ctx.text('Default black text at 12pt', 40, y, 12)
  y -= 20
  ctx.text('Colored text in red', 40, y, 12, { color: '#e74c3c' })
  y -= 20
  ctx.text('Colored text in green', 40, y, 12, { color: '#27ae60' })
  y -= 20
  ctx.text('Colored text in blue', 40, y, 12, { color: '#2980b9' })
  y -= 20
  ctx.text('Large 20pt text', 40, y, 20, { color: '#8e44ad' })
  y -= 30
  ctx.text('Small 8pt text', 40, y, 8, { color: '#555555' })
  y -= 20
  ctx.text('Special chars: (parens) \\ backslash "quotes"', 40, y, 11)

  // ── Text alignment ──
  y -= 40
  ctx.text('Text Alignment', 40, y, 18, { color: '#16213e' })
  y -= 5
  ctx.line(40, y, W - 40, y, '#cccccc', 0.5)
  y -= 25
  const boxW = W - 80
  ctx.rect(40, y - 5, boxW, 22, '#f0f0f0')
  ctx.text('Left aligned', 40, y, 12, { align: 'left', width: boxW })
  y -= 25
  ctx.rect(40, y - 5, boxW, 22, '#f0f0f0')
  ctx.text('Center aligned', 40, y, 12, { align: 'center', width: boxW })
  y -= 25
  ctx.rect(40, y - 5, boxW, 22, '#f0f0f0')
  ctx.text('Right aligned', 40, y, 12, { align: 'right', width: boxW })

  // ── measureText ──
  y -= 40
  ctx.text('measureText', 40, y, 18, { color: '#16213e' })
  y -= 25
  const sample = 'The quick brown fox jumps over the lazy dog'
  const tw = measureText(sample, 11)
  ctx.text(sample, 40, y, 11)
  y -= 3
  ctx.line(40, y, 40 + tw, y, '#e74c3c', 1.5)
  y -= 15
  ctx.text(`Measured width: ${tw.toFixed(2)}pt`, 40, y, 9, { color: '#888888' })

  // ── Rectangles ──
  y -= 35
  ctx.text('Rectangles', 40, y, 18, { color: '#16213e' })
  y -= 50
  ctx.rect(40, y, 80, 40, '#e74c3c')
  ctx.rect(140, y, 80, 40, '#f39c12')
  ctx.rect(240, y, 80, 40, '#27ae60')
  ctx.rect(340, y, 80, 40, '#2980b9')
  ctx.rect(440, y, 80, 40, '#8e44ad')
  // 3-char hex
  ctx.rect(40, y - 50, 80, 40, '#f0f')
  ctx.text('3-char hex: #f0f', 130, y - 35, 10, { color: '#333333' })

  // ── Lines ──
  y -= 110
  ctx.text('Lines', 40, y, 18, { color: '#16213e' })
  y -= 25
  ctx.line(40, y, 250, y, '#e74c3c', 1)
  ctx.text('1pt red', 260, y - 4, 9, { color: '#888' })
  y -= 15
  ctx.line(40, y, 250, y, '#2980b9', 2)
  ctx.text('2pt blue', 260, y - 4, 9, { color: '#888' })
  y -= 15
  ctx.line(40, y, 250, y, '#27ae60', 3)
  ctx.text('3pt green', 260, y - 4, 9, { color: '#888' })
  y -= 15
  ctx.line(40, y, 250, y, '#000', 0.25)
  ctx.text('0.25pt hairline', 260, y - 4, 9, { color: '#888' })

  // ── Links ──
  y -= 35
  ctx.text('Links', 40, y, 18, { color: '#16213e' })
  y -= 25
  const linkText = 'Visit GitHub (underlined link)'
  const linkW = measureText(linkText, 11)
  ctx.text(linkText, 40, y, 11, { color: '#2980b9' })
  ctx.link('https://github.com/lulzx/tinypdf', 40, y - 3, linkW, 14, { underline: '#2980b9' })
  y -= 20
  const link2 = 'Plain link (no underline)'
  const link2W = measureText(link2, 11)
  ctx.text(link2, 40, y, 11, { color: '#8e44ad' })
  ctx.link('https://example.com', 40, y - 3, link2W, 14)

  // ── Image ──
  y -= 35
  ctx.text('JPEG Image', 40, y, 18, { color: '#16213e' })
  y -= 110
  ctx.image(catJpeg, 40, y, 150, 100)
  ctx.rect(200, y, 1, 100, '#cccccc')
  ctx.text('cat.jpg embedded as', 210, y + 80, 10, { color: '#888' })
  ctx.text('DCTDecode XObject', 210, y + 66, 10, { color: '#888' })
})

// ── Page 2: Custom page size + multiple images ──────────────────────────

doc.page(500, 500, ctx => {
  ctx.rect(0, 420, 500, 80, '#2c3e50')
  ctx.text('Page 2: Custom Size (500x500)', 30, 452, 18, { color: '#ecf0f1' })

  ctx.text('This page demonstrates:', 30, 400, 12)
  ctx.text('- Custom page dimensions (500 x 500)', 40, 380, 11, { color: '#555' })
  ctx.text('- Multiple images on one page', 40, 365, 11, { color: '#555' })
  ctx.text('- Image at different sizes', 40, 350, 11, { color: '#555' })

  // Same image at 3 different sizes
  ctx.image(catJpeg, 30, 200, 120, 80)
  ctx.text('120x80', 30, 190, 9, { color: '#888' })

  ctx.image(catJpeg, 170, 210, 90, 60)
  ctx.text('90x60', 170, 200, 9, { color: '#888' })

  ctx.image(catJpeg, 280, 220, 60, 40)
  ctx.text('60x40', 280, 210, 9, { color: '#888' })

  // Footer
  ctx.line(30, 50, 470, 50, '#bdc3c7', 0.5)
  ctx.text('Generated by tinypdf', 30, 30, 9, { color: '#95a5a6' })
  ctx.text('Page 2 of 3', 400, 30, 9, { align: 'right', width: 70, color: '#95a5a6' })
})

// ── Page 3: buildStream output ──────────────────────────────────────────
// We'll build page 1-2 with build(), then demonstrate markdown() separately

const pdfBytes = doc.build()
await Bun.write(new URL('./showcase.pdf', import.meta.url).pathname, pdfBytes)
console.log(`showcase.pdf: ${(pdfBytes.length / 1024).toFixed(1)} KB (${pdfBytes.length} bytes)`)

// ── Markdown showcase ───────────────────────────────────────────────────

const md = `# Markdown Rendering

This PDF was generated from a markdown string using \`markdown()\`.

## Features

- Heading levels (h1 through h6)
- Paragraph text with automatic word wrapping
- Bullet lists with dash or asterisk markers
- Numbered lists with automatic indent

### Ordered List

1. First item
2. Second item
3. Third item

## Text Wrapping

This is a long paragraph that should automatically wrap to multiple lines. The word wrap algorithm measures each word using Helvetica glyph widths and breaks lines at the configured page width minus margins.

---

## Heading Levels

### H3 Heading
#### H4 Heading (renders as H3 size)
##### H5 Heading (renders as H3 size)
###### H6 Heading (renders as H3 size)

## Special Characters

Parentheses (like these) and backslashes \\ are escaped properly in PDF strings.

***

That was an asterisk horizontal rule above.

___

And that was an underscore horizontal rule.

## Final Notes

- Custom page size is supported via options
- Custom margins are supported via options
- Blank lines between sections add vertical spacing
- Very long words like aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa are force-broken
`

const mdBytes = markdown(md)
await Bun.write(new URL('./showcase-markdown.pdf', import.meta.url).pathname, mdBytes)
console.log(`showcase-markdown.pdf: ${(mdBytes.length / 1024).toFixed(1)} KB (${mdBytes.length} bytes)`)

// ── buildStream showcase ────────────────────────────────────────────────

const streamDoc = pdf()
streamDoc.page(W, H, ctx => {
  ctx.rect(0, H - 60, W, 60, '#16213e')
  ctx.text('buildStream() Output', 40, H - 40, 20, { color: '#ffffff' })
  ctx.text('This PDF was written via ReadableStream chunks.', 40, H - 100, 12)
  ctx.text('Each PDF object is emitted as a separate chunk,', 40, H - 118, 12)
  ctx.text('reducing peak memory for large documents.', 40, H - 136, 12)

  ctx.image(catJpeg, 40, H - 320, 200, 140)
  ctx.text('Image streaming works too!', 260, H - 250, 12, { color: '#2980b9' })

  ctx.link('https://github.com/lulzx/tinypdf', 40, H - 360, 300, 14, { underline: '#2980b9' })
  ctx.text('https://github.com/lulzx/tinypdf', 40, H - 355, 11, { color: '#2980b9' })
})

const streamPath = new URL('./showcase-stream.pdf', import.meta.url).pathname
const stream = streamDoc.buildStream()
const chunks: Uint8Array[] = []
for await (const chunk of stream) chunks.push(chunk)
const streamBytes = new Uint8Array(chunks.reduce((n, c) => n + c.length, 0))
let off = 0
for (const c of chunks) { streamBytes.set(c, off); off += c.length }
await Bun.write(streamPath, streamBytes)
console.log(`showcase-stream.pdf: ${(streamBytes.length / 1024).toFixed(1)} KB (${streamBytes.length} bytes) [via buildStream, ${chunks.length} chunks]`)
